basePath: /v1
definitions:
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.RegisterResponseModel:
    properties:
      message:
        type: string
    type: object
  models.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
  models.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  task.Adress:
    properties:
      name:
        type: string
    type: object
  task.ListTasks:
    properties:
      count:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/task.TaskReq'
        type: array
    type: object
  task.Mess:
    properties:
      message:
        type: string
    type: object
  task.Phone:
    properties:
      name:
        type: string
    type: object
  task.TaskReq:
    properties:
      assigne_id:
        type: string
      created_at:
        type: string
      deadline:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      name:
        type: string
      status:
        type: string
      summary:
        type: string
      updated_at:
        type: string
    type: object
  task.TaskRes:
    properties:
      assignee_id:
        type: string
      deadline:
        type: string
      name:
        type: string
      status:
        type: string
      summary:
        type: string
      user:
        $ref: '#/definitions/task.User'
    type: object
  task.User:
    properties:
      adress:
        items:
          $ref: '#/definitions/task.Adress'
        type: array
      bio:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      phone_numbers:
        items:
          $ref: '#/definitions/task.Phone'
        type: array
      profile_photo:
        type: string
      username:
        type: string
    type: object
  user.Adress:
    properties:
      name:
        type: string
    type: object
  user.ById:
    properties:
      userId:
        type: string
    type: object
  user.GetByemail:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.Mess:
    properties:
      message:
        type: string
    type: object
  user.Phone:
    properties:
      name:
        type: string
    type: object
  user.TaskRes:
    properties:
      assignee_id:
        type: string
      deadline:
        type: string
      id:
        type: string
      name:
        type: string
      status:
        type: string
      summary:
        type: string
    type: object
  user.UserReq:
    properties:
      acsess_token:
        type: string
      adress:
        items:
          $ref: '#/definitions/user.Adress'
        type: array
      bio:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_numbers:
        items:
          $ref: '#/definitions/user.Phone'
        type: array
      profile_photo:
        type: string
      refresh_taken:
        type: string
      tasks:
        items:
          $ref: '#/definitions/user.TaskRes'
        type: array
      updated_at:
        type: string
      username:
        type: string
    type: object
  user.UserRes:
    properties:
      acsess_token:
        type: string
      adress:
        items:
          $ref: '#/definitions/user.Adress'
        type: array
      bio:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_numbers:
        items:
          $ref: '#/definitions/user.Phone'
        type: array
      profile_photo:
        type: string
      refresh_taken:
        type: string
      tasks:
        items:
          $ref: '#/definitions/user.TaskRes'
        type: array
      username:
        type: string
    type: object
info:
  contact: {}
  description: GetMyProfile
paths:
  /login:
    put:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Email
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.GetByemail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserReq'
      summary: Login
      tags:
      - register
  /profile:
    get:
      description: GetMyProfile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserReq'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      security:
      - BearerAuth: []
      summary: GetMyProfile
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      description: Register - API for registering users
      parameters:
      - description: register
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RegisterResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: Register
      tags:
      - register
  /task/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Mess'
      summary: Delete task
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: Get task
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.TaskReq'
      summary: Get task
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: Update task
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/task.TaskReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Mess'
      summary: Update task
      tags:
      - Task
  /tasks:
    get:
      consumes:
      - application/json
      description: ListOverdue
      parameters:
      - description: Mess
        in: path
        name: mess
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.ListTasks'
      summary: ListOverdue
      tags:
      - Task
    post:
      consumes:
      - application/json
      description: This API for creating a new task
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/task.TaskRes'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/task.TaskReq'
      summary: Create new task
      tags:
      - Task
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.ById'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.Mess'
      summary: DeleteUser
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserReq'
      summary: GetUser
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.Mess'
      summary: Update User
      tags:
      - User
  /users:
    post:
      consumes:
      - application/json
      description: This API for creating a new user
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UserRes'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.UserReq'
      summary: Create new user
      tags:
      - User
  /verify/{code}:
    post:
      consumes:
      - application/json
      description: returns access token
      parameters:
      - description: code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: Verify
      tags:
      - register
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
