basePath: /v1
definitions:
  task.Mess:
    properties:
      message:
        type: string
    type: object
  task.Task:
    properties:
      assignee:
        type: string
      created_at:
        type: string
      deadline:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create new task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
      summary: Create new task
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: Update task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
      summary: Update task
      tags:
      - Task
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Mess'
      summary: Delete task
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: Get task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
      summary: Get task
      tags:
      - Task
swagger: "2.0"
